# Generated by Django 5.2.6 on 2025-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, help_text='Code à 4 chiffres pour réinitialiser le mot de passe', max_length=4, null=True, verbose_name='Code de réinitialisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de création du code de réinitialisation', null=True, verbose_name='Date de création du code'),
        ),
    ]
