# Generated by Django 5.2.5 on 2025-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Nom du type d'élection"),
        ),
    ]
