# Generated by Django 5.2.5 on 2025-09-10 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_types', '0002_alter_electiontype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='electiontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
