# Generated by Django 5.0 on 2026-01-20 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0015_alter_election_candidates_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasporaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('AFRIQUE', 'Afrique'), ('AMERIQUE', 'Amérique'), ('ASIE', 'Asie-Océanie'), ('EUROPE', 'Europe')], max_length=20, verbose_name='Zone diaspora')),
                ('inscrits', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'inscrits")),
                ('votants', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de votants')),
                ('taux_participation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de participation (%)')),
                ('taux_abstention', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'abstention (%)")),
                ('bulletins_nuls', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bulletins nuls')),
                ('suffrages_exprimes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suffrages valablement exprimés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaspora_stats', to='elections.election', verbose_name='Élection')),
            ],
            options={
                'verbose_name': 'Statistique diaspora',
                'verbose_name_plural': 'Statistiques diaspora',
                'ordering': ['election', 'zone'],
            },
        ),
        migrations.AddConstraint(
            model_name='diasporastat',
            constraint=models.UniqueConstraint(fields=('election', 'zone'), name='unique_stat_per_election_zone'),
        ),
    ]
