# Generated by Django 5.0 on 2026-01-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('pickup_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète du point de retrait', max_length=500, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Département où se trouve le point de retrait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='departments.department', verbose_name='Département'),
        ),
    ]
