# Generated by Django 5.2.5 on 2025-09-09 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('type', models.CharField(choices=[('presidential', 'Présidentielle'), ('legislative', 'Législative'), ('municipal', 'Municipale'), ('regional', 'Régionale'), ('european', 'Européenne'), ('other', 'Autre')], max_length=50, verbose_name="Type d'élection")),
                ('date', models.DateTimeField(verbose_name="Date de l'élection")),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=50, verbose_name='Statut')),
                ('candidates_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de candidats')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name="Pourcentage d'avancement")),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Élection',
                'verbose_name_plural': 'Élections',
                'ordering': ['-date'],
            },
        ),
    ]
