# Generated by Django 5.2.5 on 2025-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(verbose_name="Date de l'élection"),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('presidential', 'Présidentielle'), ('legislative', 'Législative'), ('senatorial', 'Sénatoriale'), ('municipal', 'Municipale'), ('regional', 'Régionale'), ('other', 'Autre')], max_length=50, verbose_name="Type d'élection"),
        ),
    ]
