# Generated by Django 5.2.5 on 2025-09-09 09:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_date_alter_election_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name': 'Élection', 'verbose_name_plural': 'Élections'},
        ),
        migrations.AlterField(
            model_name='election',
            name='candidates_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Le nombre de candidats doit être supérieur à 0.')], verbose_name='Nombre de candidats'),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='election',
            name='progress_percentage',
            field=models.IntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=25, verbose_name='Progression (%)'),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('ongoing', 'En cours'), ('completed', 'Terminée')], default='scheduled', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('presidential', 'Présidentielle'), ('legislative', 'Législative'), ('municipal', 'Municipale'), ('regional', 'Régionale'), ('european', 'Européenne')], max_length=20, verbose_name="Type d'élection"),
        ),
        migrations.AlterField(
            model_name='election',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
