# Generated by Django 5.2.5 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Une élection est active si elle est programmée ou en cours', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('presidential', 'Présidentielle'), ('legislative', 'Législative'), ('municipal', 'Municipale'), ('regional', 'Régionale'), ('senatorial', 'Sénatoriale')], max_length=20, verbose_name="Type d'élection"),
        ),
    ]
