# Generated by Django 5.2.5 on 2025-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_is_active_alter_election_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(fields=('type', 'date'), name='unique_type_per_date'),
        ),
    ]
