# Generated by Django 5.2.5 on 2025-09-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_types', '0001_initial'),
        ('elections', '0005_election_unique_type_per_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='election',
            name='unique_type_per_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='candidates_count',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='election',
            name='progress_percentage',
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Détails optionnels'),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ongoing', 'En cours'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name="État de l'élection"),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=150, verbose_name="Titre de l'élection"),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_types.electiontype', verbose_name="Type d'élection"),
        ),
    ]
