# Generated by Django 5.2.5 on 2025-09-10 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_remove_election_unique_type_per_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
    ]
