# Generated by Django 5.2.5 on 2025-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_types', '0003_electiontype_created_at_electiontype_updated_at'),
        ('elections', '0007_alter_election_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(fields=('type', 'date'), name='unique_election_type_date'),
        ),
    ]
