# Generated by Django 5.2.5 on 2025-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_unique_election_type_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidatesCount',
            field=models.IntegerField(default=0, verbose_name='Nombre de candidats'),
        ),
        migrations.AddField(
            model_name='election',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AddField(
            model_name='election',
            name='progressPercentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de progression'),
        ),
    ]
