# Generated by Django 5.2.5 on 2025-09-10 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_election_candidatescount_election_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidatesCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de candidats'),
        ),
        migrations.AlterField(
            model_name='election',
            name='progressPercentage',
            field=models.DecimalField(choices=[(25.0, '25%'), (50.0, '50%'), (75.0, '75%'), (100.0, '100%')], decimal_places=2, default=0.0, max_digits=5, verbose_name='Pourcentage de progression'),
        ),
    ]
