# Generated by Django 5.2.5 on 2025-09-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_alter_election_candidatescount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='candidatesCount',
            new_name='candidates_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='progressPercentage',
            new_name='progress_percentage',
        ),
    ]
