# Generated by Django 5.2.5 on 2025-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_rename_candidatescount_election_candidates_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='candidates_count',
            new_name='candidatesCount',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='election',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='election',
            name='progressPercentage',
            field=models.DecimalField(blank=True, choices=[(25.0, '25%'), (50.0, '50%'), (75.0, '75%'), (100.0, '100%')], decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Pourcentage de progression'),
        ),
    ]
