# Generated by Django 5.2.5 on 2025-09-17 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_rename_camelcase_fields_to_snake_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de candidats'),
        ),
    ]
