# Generated by Django 5.2.6 on 2025-09-22 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_alter_election_candidates_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de candidats'),
        ),
    ]
