# Generated by Django 5.2.6 on 2025-09-19 23:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif du bureau de vote', max_length=255, verbose_name='Nom du bureau de vote')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du bureau de vote (horaires, etc.)', null=True, verbose_name='Description')),
                ('nombre', models.CharField(blank=True, help_text="Numéro ou code d'identification du bureau", max_length=50, null=True, verbose_name="Numéro d'identification")),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Coordonnée latitude (doit être positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Coordonnée longitude (doit être positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le bureau de vote est actif', verbose_name='Bureau actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de création de l'enregistrement", verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification', verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Bureau de vote',
                'verbose_name_plural': 'Bureaux de vote',
                'db_table': 'voting_office_votingoffice',
                'ordering': ['-created_at'],
            },
        ),
    ]
