# Generated by Django 5.0 on 2026-01-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('voting_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingoffice',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète du bureau de vote', max_length=500, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='votingoffice',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'électeurs pouvant voter", null=True, verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='votingoffice',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Département où se trouve le bureau de vote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_offices', to='departments.department', verbose_name='Département'),
        ),
    ]
