# Generated by Django 5.2.6 on 2025-09-19 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election_types', '0003_electiontype_created_at_electiontype_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text="Date et heure prévues pour l'élection", verbose_name="Date et heure de l'élection")),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', help_text="Statut actuel de l'élection", max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de création de l'enregistrement", verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification', verbose_name='Mis à jour le')),
                ('type_election', models.ForeignKey(help_text="Type d'élection associé", on_delete=django.db.models.deletion.CASCADE, to='election_types.electiontype', verbose_name="Type d'élection")),
            ],
            options={
                'verbose_name': 'Calendrier électoral',
                'verbose_name_plural': 'Calendriers électoraux',
                'db_table': 'calendrier_electoral_calendrierelectoral',
                'ordering': ['-date'],
            },
        ),
    ]
