# Generated by Django 5.0 on 2026-01-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier_electoral', '0001_initial'),
        ('elections', '0015_alter_election_candidates_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrierelectoral',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Date de fin (pour les périodes)', null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='calendrierelectoral',
            name='election',
            field=models.ForeignKey(blank=True, help_text='Élection spécifique associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='elections.election', verbose_name='Élection'),
        ),
        migrations.AddField(
            model_name='calendrierelectoral',
            name='event_type',
            field=models.CharField(choices=[('election', "Jour d'élection"), ('inscription', "Période d'inscription"), ('campagne', 'Campagne électorale'), ('resultats', 'Proclamation des résultats'), ('contentieux', 'Délai de contentieux'), ('autre', 'Autre')], default='election', help_text="Type d'événement du calendrier", max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='calendrierelectoral',
            name='title',
            field=models.CharField(blank=True, help_text="Titre descriptif de l'événement", max_length=255, null=True, verbose_name="Titre de l'événement"),
        ),
        migrations.AlterField(
            model_name='calendrierelectoral',
            name='date',
            field=models.DateTimeField(help_text='Date et heure prévues', verbose_name="Date et heure de l'événement"),
        ),
        migrations.AlterField(
            model_name='calendrierelectoral',
            name='status',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', help_text='Statut actuel', max_length=20, verbose_name='Statut'),
        ),
    ]
