# Generated by Django 5.0 on 2026-01-19 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_alter_region_options_region_chef_lieu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code unique')),
                ('chef_lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chef-lieu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='regions.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='unique_department_name_per_region'),
        ),
    ]
