# Generated by Django 5.0 on 2026-01-19 13:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('elections', '0015_alter_election_candidates_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'inscrits")),
                ('votants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de votants')),
                ('taux_participation', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de participation (%)')),
                ('taux_abstention', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'abstention (%)")),
                ('bulletins_nuls', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bulletins nuls')),
                ('suffrages_exprimes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suffrages valablement exprimés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_stats', to='departments.department', verbose_name='Département')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stats', to='elections.election', verbose_name='Élection')),
            ],
            options={
                'verbose_name': 'Statistique départementale',
                'verbose_name_plural': 'Statistiques départementales',
                'ordering': ['election', 'department__region', 'department'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentstat',
            constraint=models.UniqueConstraint(fields=('election', 'department'), name='unique_stat_per_election_department'),
        ),
    ]
