# Generated by Django 5.0 on 2026-01-19 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstat',
            name='inscrits',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'inscrits"),
        ),
        migrations.AlterField(
            model_name='departmentstat',
            name='suffrages_exprimes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suffrages valablement exprimés'),
        ),
        migrations.AlterField(
            model_name='departmentstat',
            name='taux_abstention',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'abstention (%)"),
        ),
        migrations.AlterField(
            model_name='departmentstat',
            name='taux_participation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de participation (%)'),
        ),
        migrations.AlterField(
            model_name='departmentstat',
            name='votants',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de votants'),
        ),
    ]
