# Generated by Django 5.0 on 2026-01-20 14:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_stats', '0002_alter_departmentstat_inscrits_and_more'),
        ('elections', '0015_alter_election_candidates_count'),
        ('regions', '0003_alter_region_options_region_chef_lieu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrits', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'inscrits")),
                ('votants', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de votants')),
                ('taux_participation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de participation (%)')),
                ('taux_abstention', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'abstention (%)")),
                ('bulletins_nuls', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bulletins nuls')),
                ('suffrages_exprimes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suffrages valablement exprimés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_stats', to='elections.election', verbose_name='Élection')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_stats', to='regions.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Statistique régionale',
                'verbose_name_plural': 'Statistiques régionales',
                'ordering': ['election', 'region__region_type', 'region'],
            },
        ),
        migrations.AddConstraint(
            model_name='regionstat',
            constraint=models.UniqueConstraint(fields=('election', 'region'), name='unique_stat_per_election_region'),
        ),
    ]
