# Generated by Django 6.0.3 on 2026-03-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_stats', '0003_regionstat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regionstat',
            name='unique_stat_per_election_region',
        ),
        migrations.DeleteModel(
            name='RegionStat',
        ),
    ]
