# Generated by Django 5.2.6 on 2025-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la région'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_region_name_code'),
        ),
    ]
