# Generated by Django 5.0 on 2026-01-19 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_region_name_region_unique_region_name_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region_type', 'name'], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AddField(
            model_name='region',
            name='chef_lieu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chef-lieu'),
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est active'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('national', 'Région nationale'), ('diaspora', 'Zone diaspora')], default='national', max_length=20, verbose_name='Type de région'),
        ),
        migrations.AddField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
