# Generated by Django 5.2.5 on 2025-09-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0007_alter_election_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.IntegerField(verbose_name="Nombre total d'inscrits")),
                ('total_voted', models.IntegerField(verbose_name='Nombre total de votants')),
                ('turnout_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage de participation')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_statistics', to='elections.election', verbose_name='Élection')),
            ],
            options={
                'verbose_name': 'Statistique électorale',
                'verbose_name_plural': 'Statistiques électorales',
            },
        ),
    ]
