# Generated by Django 5.2.5 on 2025-09-10 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterstatistics',
            name='total_registered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre total d'inscrits"),
        ),
        migrations.AlterField(
            model_name='voterstatistics',
            name='total_voted',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre total de votants'),
        ),
        migrations.AlterField(
            model_name='voterstatistics',
            name='turnout_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pourcentage de participation'),
        ),
    ]
