# Generated by Django 5.2.6 on 2025-09-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_types', '0003_electiontype_created_at_electiontype_updated_at'),
        ('voter_statistics', '0002_alter_voterstatistics_total_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterstatistics',
            name='election',
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='election_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voter_statistics', to='election_types.electiontype', verbose_name="Type d'élection"),
        ),
    ]
