# Generated by Django 5.2.6 on 2025-09-19 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_statistics', '0003_remove_voterstatistics_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterstatistics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
