# Generated by Django 5.0 on 2026-01-19 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_alter_election_candidates_count'),
        ('voter_statistics', '0004_voterstatistics_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterstatistics',
            options={'verbose_name': 'Statistique électorale globale', 'verbose_name_plural': 'Statistiques électorales globales'},
        ),
        migrations.RemoveField(
            model_name='voterstatistics',
            name='election_type',
        ),
        migrations.RemoveField(
            model_name='voterstatistics',
            name='total_registered',
        ),
        migrations.RemoveField(
            model_name='voterstatistics',
            name='total_voted',
        ),
        migrations.RemoveField(
            model_name='voterstatistics',
            name='turnout_percentage',
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='election',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='elections.election', verbose_name='Élection'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='inscrits_cameroun',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inscrits au Cameroun'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='inscrits_diaspora',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inscrits en Diaspora'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='taux_abstention',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'abstention (%)"),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='taux_participation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de participation (%)'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='total_bulletins_nuls',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total bulletins nuls'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='total_inscrits',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre total d'inscrits"),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='total_suffrages_exprimes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total suffrages valablement exprimés'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='total_votants',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre total de votants'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='votants_cameroun',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Votants au Cameroun'),
        ),
        migrations.AddField(
            model_name='voterstatistics',
            name='votants_diaspora',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Votants en Diaspora'),
        ),
    ]
