# Generated by Django 5.2.5 on 2025-09-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0014_alter_election_candidates_count'),
        ('political_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('partie_politique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_parties.partiepolitique')),
            ],
            options={
                'db_table': 'candidat',
            },
        ),
    ]
