# Generated by Django 5.0 on 2026-01-19 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0015_alter_election_candidates_count'),
        ('political_parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['election', 'ballot_number', 'name'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='ballot_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro sur le bulletin'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la photo'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='elections.election', verbose_name='Élection'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='partie_politique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='political_parties.partiepolitique', verbose_name='Parti politique'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddConstraint(
            model_name='candidat',
            constraint=models.UniqueConstraint(fields=('election', 'name'), name='unique_candidate_per_election'),
        ),
    ]
