# Generated by Django 5.2.6 on 2026-01-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidat_options_candidat_ballot_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['election', 'name'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='ballot_number',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='photo_url',
        ),
    ]
