"""
Données de l'élection présidentielle 2025 du Cameroun
Extraites du PDF officiel: Resultats-Officiel-Election-Presidentiel-2025.pdf
Date de l'élection: 12 octobre 2025
"""
from decimal import Decimal

# Les 12 candidats avec leur parti et résultats globaux (page 36 du PDF)
CANDIDATES_DATA = [
    {"name": "BIYA PAUL", "party": "RDPC", "ballot": 1, "votes": 2474179, "percentage": Decimal("53.66"), "rank": 1, "winner": True},
    {"name": "ISSA TCHIROMA", "party": "FSNC", "ballot": 2, "votes": 1622334, "percentage": Decimal("35.19"), "rank": 2, "winner": False},
    {"name": "LIBII LI NGUE NGUE CABRAL", "party": "PCRN", "ballot": 3, "votes": 157568, "percentage": Decimal("3.41"), "rank": 3, "winner": False},
    {"name": "BELLO BOUBA MAIGARI", "party": "UNDP", "ballot": 4, "votes": 112758, "percentage": Decimal("2.45"), "rank": 4, "winner": False},
    {"name": "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA", "party": "UDC", "ballot": 5, "votes": 76721, "percentage": Decimal("1.66"), "rank": 5, "winner": False},
    {"name": "OSIH JOSHUA NAMBANGI", "party": "SDF", "ballot": 6, "votes": 55841, "percentage": Decimal("1.21"), "rank": 6, "winner": False},
    {"name": "ATEKI SETA CAXTON", "party": "PAL", "ballot": 7, "votes": 39935, "percentage": Decimal("0.87"), "rank": 7, "winner": False},
    {"name": "IYODI HIRAM SAMUEL", "party": "FDC", "ballot": 8, "votes": 18828, "percentage": Decimal("0.40"), "rank": 8, "winner": False},
    {"name": "MATOMBA SERGE ESPOIR", "party": "PURS", "ballot": 9, "votes": 15925, "percentage": Decimal("0.35"), "rank": 9, "winner": False},
    {"name": "BOUGHA HAGBE JACQUES", "party": "MCNC", "ballot": 10, "votes": 13612, "percentage": Decimal("0.30"), "rank": 10, "winner": False},
    {"name": "KWEMO PIERRE", "party": "UMS", "ballot": 11, "votes": 12873, "percentage": Decimal("0.28"), "rank": 11, "winner": False},
    {"name": "MUNA AKERE TABENG", "party": "UNIVERS", "ballot": 12, "votes": 10252, "percentage": Decimal("0.22"), "rank": 12, "winner": False},
]

# Résultats par département - RÉGION DE L'ADAMAOUA (pages 4-5 du PDF)
DEPARTMENT_RESULTS_ADAMAOUA = {
    "Djérem": {
        "ATEKI SETA CAXTON": {"votes": 304, "percentage": Decimal("1.12")},
        "BELLO BOUBA MAIGARI": {"votes": 2462, "percentage": Decimal("9.09")},
        "BIYA PAUL": {"votes": 9033, "percentage": Decimal("33.35")},
        "BOUGHA HAGBE JACQUES": {"votes": 111, "percentage": Decimal("0.41")},
        "ISSA TCHIROMA": {"votes": 13925, "percentage": Decimal("51.42")},
        "IYODI HIRAM SAMUEL": {"votes": 71, "percentage": Decimal("0.26")},
        "KWEMO PIERRE": {"votes": 132, "percentage": Decimal("0.49")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 391, "percentage": Decimal("1.44")},
        "MATOMBA SERGE ESPOIR": {"votes": 122, "percentage": Decimal("0.45")},
        "MUNA AKERE TABENG": {"votes": 126, "percentage": Decimal("0.47")},
        "OSIH JOSHUA NAMBANGI": {"votes": 155, "percentage": Decimal("0.57")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 252, "percentage": Decimal("0.93")},
    },
    "Faro-et-Déo": {
        "ATEKI SETA CAXTON": {"votes": 438, "percentage": Decimal("1.98")},
        "BELLO BOUBA MAIGARI": {"votes": 3706, "percentage": Decimal("16.71")},
        "BIYA PAUL": {"votes": 7330, "percentage": Decimal("33.06")},
        "BOUGHA HAGBE JACQUES": {"votes": 187, "percentage": Decimal("0.84")},
        "ISSA TCHIROMA": {"votes": 9551, "percentage": Decimal("43.07")},
        "IYODI HIRAM SAMUEL": {"votes": 84, "percentage": Decimal("0.38")},
        "KWEMO PIERRE": {"votes": 135, "percentage": Decimal("0.61")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 142, "percentage": Decimal("0.64")},
        "MATOMBA SERGE ESPOIR": {"votes": 114, "percentage": Decimal("0.51")},
        "MUNA AKERE TABENG": {"votes": 118, "percentage": Decimal("0.53")},
        "OSIH JOSHUA NAMBANGI": {"votes": 93, "percentage": Decimal("0.42")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 277, "percentage": Decimal("1.25")},
    },
    "Mayo-Banyo": {
        "ATEKI SETA CAXTON": {"votes": 797, "percentage": Decimal("2.21")},
        "BELLO BOUBA MAIGARI": {"votes": 3313, "percentage": Decimal("9.19")},
        "BIYA PAUL": {"votes": 13835, "percentage": Decimal("38.37")},
        "BOUGHA HAGBE JACQUES": {"votes": 235, "percentage": Decimal("0.65")},
        "ISSA TCHIROMA": {"votes": 15602, "percentage": Decimal("43.27")},
        "IYODI HIRAM SAMUEL": {"votes": 125, "percentage": Decimal("0.35")},
        "KWEMO PIERRE": {"votes": 270, "percentage": Decimal("0.75")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 334, "percentage": Decimal("0.93")},
        "MATOMBA SERGE ESPOIR": {"votes": 300, "percentage": Decimal("0.83")},
        "MUNA AKERE TABENG": {"votes": 232, "percentage": Decimal("0.64")},
        "OSIH JOSHUA NAMBANGI": {"votes": 431, "percentage": Decimal("1.19")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 585, "percentage": Decimal("1.62")},
    },
    "Mbéré": {
        "ATEKI SETA CAXTON": {"votes": 604, "percentage": Decimal("1.58")},
        "BELLO BOUBA MAIGARI": {"votes": 2227, "percentage": Decimal("5.81")},
        "BIYA PAUL": {"votes": 19883, "percentage": Decimal("51.88")},
        "BOUGHA HAGBE JACQUES": {"votes": 339, "percentage": Decimal("0.88")},
        "ISSA TCHIROMA": {"votes": 13431, "percentage": Decimal("35.05")},
        "IYODI HIRAM SAMUEL": {"votes": 147, "percentage": Decimal("0.38")},
        "KWEMO PIERRE": {"votes": 143, "percentage": Decimal("0.37")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 789, "percentage": Decimal("2.06")},
        "MATOMBA SERGE ESPOIR": {"votes": 186, "percentage": Decimal("0.49")},
        "MUNA AKERE TABENG": {"votes": 105, "percentage": Decimal("0.27")},
        "OSIH JOSHUA NAMBANGI": {"votes": 123, "percentage": Decimal("0.32")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 348, "percentage": Decimal("0.91")},
    },
    "Vina": {
        "ATEKI SETA CAXTON": {"votes": 854, "percentage": Decimal("0.81")},
        "BELLO BOUBA MAIGARI": {"votes": 8036, "percentage": Decimal("7.63")},
        "BIYA PAUL": {"votes": 29175, "percentage": Decimal("27.69")},
        "BOUGHA HAGBE JACQUES": {"votes": 344, "percentage": Decimal("0.33")},
        "ISSA TCHIROMA": {"votes": 62749, "percentage": Decimal("59.56")},
        "IYODI HIRAM SAMUEL": {"votes": 277, "percentage": Decimal("0.26")},
        "KWEMO PIERRE": {"votes": 259, "percentage": Decimal("0.24")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1758, "percentage": Decimal("1.67")},
        "MATOMBA SERGE ESPOIR": {"votes": 298, "percentage": Decimal("0.28")},
        "MUNA AKERE TABENG": {"votes": 283, "percentage": Decimal("0.27")},
        "OSIH JOSHUA NAMBANGI": {"votes": 505, "percentage": Decimal("0.48")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 819, "percentage": Decimal("0.78")},
    },
}

# Résultats par département - RÉGION DU CENTRE (pages 6-8 du PDF)
DEPARTMENT_RESULTS_CENTRE = {
    "Haute-Sanaga": {
        "ATEKI SETA CAXTON": {"votes": 35, "percentage": Decimal("0.06")},
        "BELLO BOUBA MAIGARI": {"votes": 390, "percentage": Decimal("0.68")},
        "BIYA PAUL": {"votes": 51263, "percentage": Decimal("89.48")},
        "BOUGHA HAGBE JACQUES": {"votes": 31, "percentage": Decimal("0.05")},
        "ISSA TCHIROMA": {"votes": 4254, "percentage": Decimal("7.43")},
        "IYODI HIRAM SAMUEL": {"votes": 65, "percentage": Decimal("0.11")},
        "KWEMO PIERRE": {"votes": 26, "percentage": Decimal("0.05")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 967, "percentage": Decimal("1.69")},
        "MATOMBA SERGE ESPOIR": {"votes": 71, "percentage": Decimal("0.12")},
        "MUNA AKERE TABENG": {"votes": 43, "percentage": Decimal("0.08")},
        "OSIH JOSHUA NAMBANGI": {"votes": 83, "percentage": Decimal("0.15")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 60, "percentage": Decimal("0.10")},
    },
    "Lékié": {
        "ATEKI SETA CAXTON": {"votes": 254, "percentage": Decimal("0.17")},
        "BELLO BOUBA MAIGARI": {"votes": 310, "percentage": Decimal("0.21")},
        "BIYA PAUL": {"votes": 135236, "percentage": Decimal("91.39")},
        "BOUGHA HAGBE JACQUES": {"votes": 57, "percentage": Decimal("0.04")},
        "ISSA TCHIROMA": {"votes": 7143, "percentage": Decimal("4.83")},
        "IYODI HIRAM SAMUEL": {"votes": 322, "percentage": Decimal("0.22")},
        "KWEMO PIERRE": {"votes": 68, "percentage": Decimal("0.05")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 3867, "percentage": Decimal("2.61")},
        "MATOMBA SERGE ESPOIR": {"votes": 163, "percentage": Decimal("0.11")},
        "MUNA AKERE TABENG": {"votes": 47, "percentage": Decimal("0.03")},
        "OSIH JOSHUA NAMBANGI": {"votes": 316, "percentage": Decimal("0.21")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 188, "percentage": Decimal("0.13")},
    },
    "Mbam-et-Inoubou": {
        "ATEKI SETA CAXTON": {"votes": 289, "percentage": Decimal("0.34")},
        "BELLO BOUBA MAIGARI": {"votes": 436, "percentage": Decimal("0.51")},
        "BIYA PAUL": {"votes": 70783, "percentage": Decimal("83.19")},
        "BOUGHA HAGBE JACQUES": {"votes": 121, "percentage": Decimal("0.14")},
        "ISSA TCHIROMA": {"votes": 8402, "percentage": Decimal("9.87")},
        "IYODI HIRAM SAMUEL": {"votes": 231, "percentage": Decimal("0.27")},
        "KWEMO PIERRE": {"votes": 125, "percentage": Decimal("0.15")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 3359, "percentage": Decimal("3.95")},
        "MATOMBA SERGE ESPOIR": {"votes": 548, "percentage": Decimal("0.64")},
        "MUNA AKERE TABENG": {"votes": 86, "percentage": Decimal("0.10")},
        "OSIH JOSHUA NAMBANGI": {"votes": 387, "percentage": Decimal("0.46")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 320, "percentage": Decimal("0.38")},
    },
    "Mbam-et-Kim": {
        "ATEKI SETA CAXTON": {"votes": 185, "percentage": Decimal("0.31")},
        "BELLO BOUBA MAIGARI": {"votes": 471, "percentage": Decimal("0.79")},
        "BIYA PAUL": {"votes": 52692, "percentage": Decimal("88.03")},
        "BOUGHA HAGBE JACQUES": {"votes": 77, "percentage": Decimal("0.13")},
        "ISSA TCHIROMA": {"votes": 4197, "percentage": Decimal("7.01")},
        "IYODI HIRAM SAMUEL": {"votes": 140, "percentage": Decimal("0.23")},
        "KWEMO PIERRE": {"votes": 88, "percentage": Decimal("0.15")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1206, "percentage": Decimal("2.01")},
        "MATOMBA SERGE ESPOIR": {"votes": 173, "percentage": Decimal("0.29")},
        "MUNA AKERE TABENG": {"votes": 90, "percentage": Decimal("0.15")},
        "OSIH JOSHUA NAMBANGI": {"votes": 366, "percentage": Decimal("0.61")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 175, "percentage": Decimal("0.29")},
    },
    "Méfou-et-Afamba": {
        "ATEKI SETA CAXTON": {"votes": 77, "percentage": Decimal("0.07")},
        "BELLO BOUBA MAIGARI": {"votes": 247, "percentage": Decimal("0.24")},
        "BIYA PAUL": {"votes": 80590, "percentage": Decimal("76.93")},
        "BOUGHA HAGBE JACQUES": {"votes": 85, "percentage": Decimal("0.08")},
        "ISSA TCHIROMA": {"votes": 18205, "percentage": Decimal("17.38")},
        "IYODI HIRAM SAMUEL": {"votes": 339, "percentage": Decimal("0.32")},
        "KWEMO PIERRE": {"votes": 50, "percentage": Decimal("0.05")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 4504, "percentage": Decimal("4.30")},
        "MATOMBA SERGE ESPOIR": {"votes": 144, "percentage": Decimal("0.14")},
        "MUNA AKERE TABENG": {"votes": 58, "percentage": Decimal("0.05")},
        "OSIH JOSHUA NAMBANGI": {"votes": 295, "percentage": Decimal("0.28")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 168, "percentage": Decimal("0.16")},
    },
    "Méfou-et-Akono": {
        "ATEKI SETA CAXTON": {"votes": 52, "percentage": Decimal("0.17")},
        "BELLO BOUBA MAIGARI": {"votes": 117, "percentage": Decimal("0.38")},
        "BIYA PAUL": {"votes": 24806, "percentage": Decimal("80.33")},
        "BOUGHA HAGBE JACQUES": {"votes": 55, "percentage": Decimal("0.18")},
        "ISSA TCHIROMA": {"votes": 4227, "percentage": Decimal("13.69")},
        "IYODI HIRAM SAMUEL": {"votes": 75, "percentage": Decimal("0.24")},
        "KWEMO PIERRE": {"votes": 20, "percentage": Decimal("0.07")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1297, "percentage": Decimal("4.20")},
        "MATOMBA SERGE ESPOIR": {"votes": 63, "percentage": Decimal("0.20")},
        "MUNA AKERE TABENG": {"votes": 27, "percentage": Decimal("0.09")},
        "OSIH JOSHUA NAMBANGI": {"votes": 69, "percentage": Decimal("0.22")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 71, "percentage": Decimal("0.23")},
    },
    "Mfoundi": {
        "ATEKI SETA CAXTON": {"votes": 377, "percentage": Decimal("0.10")},
        "BELLO BOUBA MAIGARI": {"votes": 2081, "percentage": Decimal("0.53")},
        "BIYA PAUL": {"votes": 179394, "percentage": Decimal("45.92")},
        "BOUGHA HAGBE JACQUES": {"votes": 319, "percentage": Decimal("0.08")},
        "ISSA TCHIROMA": {"votes": 170874, "percentage": Decimal("43.74")},
        "IYODI HIRAM SAMUEL": {"votes": 2999, "percentage": Decimal("0.77")},
        "KWEMO PIERRE": {"votes": 424, "percentage": Decimal("0.11")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 28378, "percentage": Decimal("7.27")},
        "MATOMBA SERGE ESPOIR": {"votes": 1071, "percentage": Decimal("0.27")},
        "MUNA AKERE TABENG": {"votes": 443, "percentage": Decimal("0.11")},
        "OSIH JOSHUA NAMBANGI": {"votes": 2650, "percentage": Decimal("0.68")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1630, "percentage": Decimal("0.42")},
    },
    "Nyong-et-Kellé": {
        "ATEKI SETA CAXTON": {"votes": 66, "percentage": Decimal("0.12")},
        "BELLO BOUBA MAIGARI": {"votes": 122, "percentage": Decimal("0.21")},
        "BIYA PAUL": {"votes": 38559, "percentage": Decimal("67.62")},
        "BOUGHA HAGBE JACQUES": {"votes": 159, "percentage": Decimal("0.28")},
        "ISSA TCHIROMA": {"votes": 1571, "percentage": Decimal("2.76")},
        "IYODI HIRAM SAMUEL": {"votes": 74, "percentage": Decimal("0.13")},
        "KWEMO PIERRE": {"votes": 59, "percentage": Decimal("0.10")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 16015, "percentage": Decimal("28.08")},
        "MATOMBA SERGE ESPOIR": {"votes": 192, "percentage": Decimal("0.34")},
        "MUNA AKERE TABENG": {"votes": 22, "percentage": Decimal("0.04")},
        "OSIH JOSHUA NAMBANGI": {"votes": 81, "percentage": Decimal("0.14")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 104, "percentage": Decimal("0.18")},
    },
    "Nyong-et-Mfoumou": {
        "ATEKI SETA CAXTON": {"votes": 29, "percentage": Decimal("0.07")},
        "BELLO BOUBA MAIGARI": {"votes": 22, "percentage": Decimal("0.06")},
        "BIYA PAUL": {"votes": 38753, "percentage": Decimal("97.32")},
        "BOUGHA HAGBE JACQUES": {"votes": 6, "percentage": Decimal("0.02")},
        "ISSA TCHIROMA": {"votes": 456, "percentage": Decimal("1.14")},
        "IYODI HIRAM SAMUEL": {"votes": 21, "percentage": Decimal("0.05")},
        "KWEMO PIERRE": {"votes": 4, "percentage": Decimal("0.01")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 468, "percentage": Decimal("1.17")},
        "MATOMBA SERGE ESPOIR": {"votes": 12, "percentage": Decimal("0.03")},
        "MUNA AKERE TABENG": {"votes": 7, "percentage": Decimal("0.02")},
        "OSIH JOSHUA NAMBANGI": {"votes": 12, "percentage": Decimal("0.03")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 31, "percentage": Decimal("0.08")},
    },
    "Nyong-et-So'o": {
        "ATEKI SETA CAXTON": {"votes": 85, "percentage": Decimal("0.15")},
        "BELLO BOUBA MAIGARI": {"votes": 135, "percentage": Decimal("0.24")},
        "BIYA PAUL": {"votes": 50077, "percentage": Decimal("88.95")},
        "BOUGHA HAGBE JACQUES": {"votes": 39, "percentage": Decimal("0.07")},
        "ISSA TCHIROMA": {"votes": 3325, "percentage": Decimal("5.91")},
        "IYODI HIRAM SAMUEL": {"votes": 73, "percentage": Decimal("0.13")},
        "KWEMO PIERRE": {"votes": 16, "percentage": Decimal("0.03")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 2057, "percentage": Decimal("3.65")},
        "MATOMBA SERGE ESPOIR": {"votes": 185, "percentage": Decimal("0.33")},
        "MUNA AKERE TABENG": {"votes": 46, "percentage": Decimal("0.08")},
        "OSIH JOSHUA NAMBANGI": {"votes": 177, "percentage": Decimal("0.31")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 82, "percentage": Decimal("0.15")},
    },
}

# Statistiques par département - RÉGION DE L'ADAMAOUA (page 4 du PDF)
DEPARTMENT_STATS_ADAMAOUA = {
    "Djérem": {
        "inscrits": 63683,
        "votants": 27426,
        "taux_participation": Decimal("43.07"),
        "taux_abstention": Decimal("56.93"),
        "bulletins_nuls": 342,
        "suffrages_exprimes": 27084
    },
    "Faro-et-Déo": {
        "inscrits": 45265,
        "votants": 22460,
        "taux_participation": Decimal("49.62"),
        "taux_abstention": Decimal("50.38"),
        "bulletins_nuls": 285,
        "suffrages_exprimes": 22175
    },
    "Mayo-Banyo": {
        "inscrits": 82424,
        "votants": 36690,
        "taux_participation": Decimal("44.51"),
        "taux_abstention": Decimal("55.49"),
        "bulletins_nuls": 631,
        "suffrages_exprimes": 36059
    },
    "Mbéré": {
        "inscrits": 81656,
        "votants": 38866,
        "taux_participation": Decimal("47.6"),
        "taux_abstention": Decimal("52.4"),
        "bulletins_nuls": 541,
        "suffrages_exprimes": 38325
    },
    "Vina": {
        "inscrits": 238904,
        "votants": 106654,
        "taux_participation": Decimal("44.64"),
        "taux_abstention": Decimal("55.36"),
        "bulletins_nuls": 1297,
        "suffrages_exprimes": 105357
    },
}

# Statistiques par département - RÉGION DU CENTRE (page 6 du PDF)
DEPARTMENT_STATS_CENTRE = {
    "Haute-Sanaga": {
        "inscrits": 60701,
        "votants": 57560,
        "taux_participation": Decimal("94.83"),
        "taux_abstention": Decimal("5.17"),
        "bulletins_nuls": 272,
        "suffrages_exprimes": 57288
    },
    "Lékié": {
        "inscrits": 160527,
        "votants": 148985,
        "taux_participation": Decimal("92.81"),
        "taux_abstention": Decimal("7.19"),
        "bulletins_nuls": 1014,
        "suffrages_exprimes": 147971
    },
    "Mbam-et-Inoubou": {
        "inscrits": 94177,
        "votants": 85872,
        "taux_participation": Decimal("91.18"),
        "taux_abstention": Decimal("8.82"),
        "bulletins_nuls": 785,
        "suffrages_exprimes": 85087
    },
    "Mbam-et-Kim": {
        "inscrits": 65022,
        "votants": 60333,
        "taux_participation": Decimal("92.79"),
        "taux_abstention": Decimal("7.21"),
        "bulletins_nuls": 473,
        "suffrages_exprimes": 59860
    },
    "Méfou-et-Afamba": {
        "inscrits": 112313,
        "votants": 105425,
        "taux_participation": Decimal("93.87"),
        "taux_abstention": Decimal("6.13"),
        "bulletins_nuls": 663,
        "suffrages_exprimes": 104762
    },
    "Méfou-et-Akono": {
        "inscrits": 46103,
        "votants": 31173,
        "taux_participation": Decimal("67.62"),
        "taux_abstention": Decimal("32.38"),
        "bulletins_nuls": 294,
        "suffrages_exprimes": 30879
    },
    "Mfoundi": {
        "inscrits": 771503,
        "votants": 393708,
        "taux_participation": Decimal("51.03"),
        "taux_abstention": Decimal("48.97"),
        "bulletins_nuls": 3068,
        "suffrages_exprimes": 390640
    },
    "Nyong-et-Kellé": {
        "inscrits": 62917,
        "votants": 57255,
        "taux_participation": Decimal("91"),
        "taux_abstention": Decimal("9"),
        "bulletins_nuls": 231,
        "suffrages_exprimes": 57024
    },
    "Nyong-et-Mfoumou": {
        "inscrits": 50190,
        "votants": 39955,
        "taux_participation": Decimal("79.61"),
        "taux_abstention": Decimal("20.39"),
        "bulletins_nuls": 134,
        "suffrages_exprimes": 39821
    },
    "Nyong-et-So'o": {
        "inscrits": 60894,
        "votants": 56621,
        "taux_participation": Decimal("92.98"),
        "taux_abstention": Decimal("7.02"),
        "bulletins_nuls": 324,
        "suffrages_exprimes": 56297
    },
}

# Résultats par département - RÉGION DE L'EST (pages 9-10 du PDF)
DEPARTMENT_RESULTS_EST = {
    "Boumba-et-Ngoko": {
        "ATEKI SETA CAXTON": {"votes": 171, "percentage": Decimal("0.63")},
        "BELLO BOUBA MAIGARI": {"votes": 504, "percentage": Decimal("1.86")},
        "BIYA PAUL": {"votes": 21904, "percentage": Decimal("80.81")},
        "BOUGHA HAGBE JACQUES": {"votes": 93, "percentage": Decimal("0.34")},
        "ISSA TCHIROMA": {"votes": 2931, "percentage": Decimal("10.81")},
        "IYODI HIRAM SAMUEL": {"votes": 138, "percentage": Decimal("0.51")},
        "KWEMO PIERRE": {"votes": 93, "percentage": Decimal("0.34")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 916, "percentage": Decimal("3.39")},
        "MATOMBA SERGE ESPOIR": {"votes": 96, "percentage": Decimal("0.35")},
        "MUNA AKERE TABENG": {"votes": 37, "percentage": Decimal("0.14")},
        "OSIH JOSHUA NAMBANGI": {"votes": 110, "percentage": Decimal("0.41")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 111, "percentage": Decimal("0.41")},
    },
    "Haut-Nyong": {
        "ATEKI SETA CAXTON": {"votes": 461, "percentage": Decimal("0.63")},
        "BELLO BOUBA MAIGARI": {"votes": 284, "percentage": Decimal("0.39")},
        "BIYA PAUL": {"votes": 67491, "percentage": Decimal("91.97")},
        "BOUGHA HAGBE JACQUES": {"votes": 47, "percentage": Decimal("0.06")},
        "ISSA TCHIROMA": {"votes": 3306, "percentage": Decimal("4.50")},
        "IYODI HIRAM SAMUEL": {"votes": 71, "percentage": Decimal("0.10")},
        "KWEMO PIERRE": {"votes": 34, "percentage": Decimal("0.05")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1269, "percentage": Decimal("1.73")},
        "MATOMBA SERGE ESPOIR": {"votes": 74, "percentage": Decimal("0.10")},
        "MUNA AKERE TABENG": {"votes": 39, "percentage": Decimal("0.05")},
        "OSIH JOSHUA NAMBANGI": {"votes": 182, "percentage": Decimal("0.25")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 128, "percentage": Decimal("0.17")},
    },
    "Kadey": {
        "ATEKI SETA CAXTON": {"votes": 477, "percentage": Decimal("0.64")},
        "BELLO BOUBA MAIGARI": {"votes": 727, "percentage": Decimal("0.98")},
        "BIYA PAUL": {"votes": 64070, "percentage": Decimal("86.59")},
        "BOUGHA HAGBE JACQUES": {"votes": 398, "percentage": Decimal("0.54")},
        "ISSA TCHIROMA": {"votes": 6869, "percentage": Decimal("9.28")},
        "IYODI HIRAM SAMUEL": {"votes": 94, "percentage": Decimal("0.13")},
        "KWEMO PIERRE": {"votes": 116, "percentage": Decimal("0.16")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 638, "percentage": Decimal("0.86")},
        "MATOMBA SERGE ESPOIR": {"votes": 126, "percentage": Decimal("0.17")},
        "MUNA AKERE TABENG": {"votes": 71, "percentage": Decimal("0.1")},
        "OSIH JOSHUA NAMBANGI": {"votes": 108, "percentage": Decimal("0.15")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 295, "percentage": Decimal("0.40")},
    },
    "Lom-et-Djérem": {
        "ATEKI SETA CAXTON": {"votes": 569, "percentage": Decimal("0.66")},
        "BELLO BOUBA MAIGARI": {"votes": 2318, "percentage": Decimal("2.69")},
        "BIYA PAUL": {"votes": 39078, "percentage": Decimal("45.38")},
        "BOUGHA HAGBE JACQUES": {"votes": 206, "percentage": Decimal("0.24")},
        "ISSA TCHIROMA": {"votes": 38554, "percentage": Decimal("44.77")},
        "IYODI HIRAM SAMUEL": {"votes": 362, "percentage": Decimal("0.42")},
        "KWEMO PIERRE": {"votes": 192, "percentage": Decimal("0.22")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 3391, "percentage": Decimal("3.94")},
        "MATOMBA SERGE ESPOIR": {"votes": 391, "percentage": Decimal("0.45")},
        "MUNA AKERE TABENG": {"votes": 208, "percentage": Decimal("0.24")},
        "OSIH JOSHUA NAMBANGI": {"votes": 384, "percentage": Decimal("0.45")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 469, "percentage": Decimal("0.54")},
    },
}

# Statistiques par département - RÉGION DE L'EST (page 9 du PDF)
DEPARTMENT_STATS_EST = {
    "Boumba-et-Ngoko": {
        "inscrits": 44931,
        "votants": 27423,
        "taux_participation": Decimal("61.03"),
        "taux_abstention": Decimal("38.97"),
        "bulletins_nuls": 319,
        "suffrages_exprimes": 27104
    },
    "Haut-Nyong": {
        "inscrits": 93665,
        "votants": 73840,
        "taux_participation": Decimal("78.83"),
        "taux_abstention": Decimal("21.17"),
        "bulletins_nuls": 454,
        "suffrages_exprimes": 73386
    },
    "Kadey": {
        "inscrits": 76540,
        "votants": 74647,
        "taux_participation": Decimal("97.53"),
        "taux_abstention": Decimal("2.47"),
        "bulletins_nuls": 658,
        "suffrages_exprimes": 73989
    },
    "Lom-et-Djérem": {
        "inscrits": 179223,
        "votants": 87415,
        "taux_participation": Decimal("48.77"),
        "taux_abstention": Decimal("51.23"),
        "bulletins_nuls": 1293,
        "suffrages_exprimes": 86122
    },
}

# Résultats par département - RÉGION DE L'EXTRÊME-NORD (pages 11-12 du PDF)
DEPARTMENT_RESULTS_EXTREME_NORD = {
    "Diamaré": {
        "ATEKI SETA CAXTON": {"votes": 4415, "percentage": Decimal("2.67")},
        "BELLO BOUBA MAIGARI": {"votes": 5281, "percentage": Decimal("3.19")},
        "BIYA PAUL": {"votes": 70040, "percentage": Decimal("42.30")},
        "BOUGHA HAGBE JACQUES": {"votes": 557, "percentage": Decimal("0.34")},
        "ISSA TCHIROMA": {"votes": 79744, "percentage": Decimal("48.16")},
        "IYODI HIRAM SAMUEL": {"votes": 399, "percentage": Decimal("0.24")},
        "KWEMO PIERRE": {"votes": 697, "percentage": Decimal("0.42")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1170, "percentage": Decimal("0.71")},
        "MATOMBA SERGE ESPOIR": {"votes": 528, "percentage": Decimal("0.32")},
        "MUNA AKERE TABENG": {"votes": 421, "percentage": Decimal("0.25")},
        "OSIH JOSHUA NAMBANGI": {"votes": 506, "percentage": Decimal("0.31")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1809, "percentage": Decimal("1.09")},
    },
    "Logone-et-Chari": {
        "ATEKI SETA CAXTON": {"votes": 2243, "percentage": Decimal("1.87")},
        "BELLO BOUBA MAIGARI": {"votes": 4004, "percentage": Decimal("3.34")},
        "BIYA PAUL": {"votes": 68549, "percentage": Decimal("57.17")},
        "BOUGHA HAGBE JACQUES": {"votes": 302, "percentage": Decimal("0.25")},
        "ISSA TCHIROMA": {"votes": 42388, "percentage": Decimal("35.35")},
        "IYODI HIRAM SAMUEL": {"votes": 204, "percentage": Decimal("0.17")},
        "KWEMO PIERRE": {"votes": 324, "percentage": Decimal("0.27")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 710, "percentage": Decimal("0.59")},
        "MATOMBA SERGE ESPOIR": {"votes": 232, "percentage": Decimal("0.19")},
        "MUNA AKERE TABENG": {"votes": 205, "percentage": Decimal("0.17")},
        "OSIH JOSHUA NAMBANGI": {"votes": 222, "percentage": Decimal("0.19")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 524, "percentage": Decimal("0.44")},
    },
    "Mayo-Danay": {
        "ATEKI SETA CAXTON": {"votes": 3189, "percentage": Decimal("2.29")},
        "BELLO BOUBA MAIGARI": {"votes": 4945, "percentage": Decimal("3.55")},
        "BIYA PAUL": {"votes": 57752, "percentage": Decimal("41.44")},
        "BOUGHA HAGBE JACQUES": {"votes": 740, "percentage": Decimal("0.53")},
        "ISSA TCHIROMA": {"votes": 65793, "percentage": Decimal("47.21")},
        "IYODI HIRAM SAMUEL": {"votes": 537, "percentage": Decimal("0.39")},
        "KWEMO PIERRE": {"votes": 735, "percentage": Decimal("0.53")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1908, "percentage": Decimal("1.37")},
        "MATOMBA SERGE ESPOIR": {"votes": 571, "percentage": Decimal("0.41")},
        "MUNA AKERE TABENG": {"votes": 508, "percentage": Decimal("0.36")},
        "OSIH JOSHUA NAMBANGI": {"votes": 947, "percentage": Decimal("0.68")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1733, "percentage": Decimal("1.24")},
    },
    "Mayo-Kani": {
        "ATEKI SETA CAXTON": {"votes": 3101, "percentage": Decimal("3.23")},
        "BELLO BOUBA MAIGARI": {"votes": 4234, "percentage": Decimal("4.41")},
        "BIYA PAUL": {"votes": 40518, "percentage": Decimal("42.22")},
        "BOUGHA HAGBE JACQUES": {"votes": 594, "percentage": Decimal("0.62")},
        "ISSA TCHIROMA": {"votes": 40749, "percentage": Decimal("42.46")},
        "IYODI HIRAM SAMUEL": {"votes": 497, "percentage": Decimal("0.52")},
        "KWEMO PIERRE": {"votes": 652, "percentage": Decimal("0.68")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 2382, "percentage": Decimal("2.48")},
        "MATOMBA SERGE ESPOIR": {"votes": 507, "percentage": Decimal("0.53")},
        "MUNA AKERE TABENG": {"votes": 422, "percentage": Decimal("0.44")},
        "OSIH JOSHUA NAMBANGI": {"votes": 703, "percentage": Decimal("0.73")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1606, "percentage": Decimal("1.68")},
    },
    "Mayo-Sava": {
        "ATEKI SETA CAXTON": {"votes": 1424, "percentage": Decimal("1.65")},
        "BELLO BOUBA MAIGARI": {"votes": 1714, "percentage": Decimal("1.99")},
        "BIYA PAUL": {"votes": 55203, "percentage": Decimal("64.04")},
        "BOUGHA HAGBE JACQUES": {"votes": 568, "percentage": Decimal("0.66")},
        "ISSA TCHIROMA": {"votes": 24885, "percentage": Decimal("28.87")},
        "IYODI HIRAM SAMUEL": {"votes": 249, "percentage": Decimal("0.29")},
        "KWEMO PIERRE": {"votes": 266, "percentage": Decimal("0.31")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 338, "percentage": Decimal("0.39")},
        "MATOMBA SERGE ESPOIR": {"votes": 215, "percentage": Decimal("0.25")},
        "MUNA AKERE TABENG": {"votes": 205, "percentage": Decimal("0.24")},
        "OSIH JOSHUA NAMBANGI": {"votes": 462, "percentage": Decimal("0.53")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 675, "percentage": Decimal("0.78")},
    },
    "Mayo-Tsanaga": {
        "ATEKI SETA CAXTON": {"votes": 4501, "percentage": Decimal("4.08")},
        "BELLO BOUBA MAIGARI": {"votes": 8600, "percentage": Decimal("7.80")},
        "BIYA PAUL": {"votes": 37414, "percentage": Decimal("33.92")},
        "BOUGHA HAGBE JACQUES": {"votes": 1457, "percentage": Decimal("1.32")},
        "ISSA TCHIROMA": {"votes": 50110, "percentage": Decimal("45.43")},
        "IYODI HIRAM SAMUEL": {"votes": 731, "percentage": Decimal("0.66")},
        "KWEMO PIERRE": {"votes": 1058, "percentage": Decimal("0.96")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1274, "percentage": Decimal("1.16")},
        "MATOMBA SERGE ESPOIR": {"votes": 659, "percentage": Decimal("0.60")},
        "MUNA AKERE TABENG": {"votes": 661, "percentage": Decimal("0.60")},
        "OSIH JOSHUA NAMBANGI": {"votes": 677, "percentage": Decimal("0.61")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 3150, "percentage": Decimal("2.86")},
    },
}

# Statistiques par département - RÉGION DE L'EXTRÊME-NORD (page 11 du PDF)
DEPARTMENT_STATS_EXTREME_NORD = {
    "Diamaré": {
        "inscrits": 305771,
        "votants": 169046,
        "taux_participation": Decimal("55.29"),
        "taux_abstention": Decimal("44.71"),
        "bulletins_nuls": 3479,
        "suffrages_exprimes": 165567
    },
    "Logone-et-Chari": {
        "inscrits": 215294,
        "votants": 122890,
        "taux_participation": Decimal("57.08"),
        "taux_abstention": Decimal("42.92"),
        "bulletins_nuls": 2983,
        "suffrages_exprimes": 119907
    },
    "Mayo-Danay": {
        "inscrits": 218740,
        "votants": 142416,
        "taux_participation": Decimal("65.11"),
        "taux_abstention": Decimal("34.89"),
        "bulletins_nuls": 3058,
        "suffrages_exprimes": 139358
    },
    "Mayo-Kani": {
        "inscrits": 158265,
        "votants": 98313,
        "taux_participation": Decimal("62.12"),
        "taux_abstention": Decimal("37.88"),
        "bulletins_nuls": 2348,
        "suffrages_exprimes": 95965
    },
    "Mayo-Sava": {
        "inscrits": 146095,
        "votants": 88373,
        "taux_participation": Decimal("60.49"),
        "taux_abstention": Decimal("39.51"),
        "bulletins_nuls": 2169,
        "suffrages_exprimes": 86204
    },
    "Mayo-Tsanaga": {
        "inscrits": 217430,
        "votants": 113624,
        "taux_participation": Decimal("52.26"),
        "taux_abstention": Decimal("47.74"),
        "bulletins_nuls": 3332,
        "suffrages_exprimes": 110292
    },
}

# Résultats par département - RÉGION DU LITTORAL (pages 13-14 du PDF)
DEPARTMENT_RESULTS_LITTORAL = {
    "Moungo": {
        "ATEKI SETA CAXTON": {"votes": 535, "percentage": Decimal("0.45")},
        "BELLO BOUBA MAIGARI": {"votes": 2887, "percentage": Decimal("2.41")},
        "BIYA PAUL": {"votes": 48134, "percentage": Decimal("40.16")},
        "BOUGHA HAGBE JACQUES": {"votes": 249, "percentage": Decimal("0.21")},
        "ISSA TCHIROMA": {"votes": 57595, "percentage": Decimal("48.05")},
        "IYODI HIRAM SAMUEL": {"votes": 530, "percentage": Decimal("0.44")},
        "KWEMO PIERRE": {"votes": 919, "percentage": Decimal("0.76")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 2795, "percentage": Decimal("2.33")},
        "MATOMBA SERGE ESPOIR": {"votes": 1029, "percentage": Decimal("0.86")},
        "MUNA AKERE TABENG": {"votes": 329, "percentage": Decimal("0.27")},
        "OSIH JOSHUA NAMBANGI": {"votes": 3917, "percentage": Decimal("3.27")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 942, "percentage": Decimal("0.79")},
    },
    "Nkam": {
        "ATEKI SETA CAXTON": {"votes": 86, "percentage": Decimal("0.59")},
        "BELLO BOUBA MAIGARI": {"votes": 245, "percentage": Decimal("1.68")},
        "BIYA PAUL": {"votes": 8173, "percentage": Decimal("55.88")},
        "BOUGHA HAGBE JACQUES": {"votes": 34, "percentage": Decimal("0.23")},
        "ISSA TCHIROMA": {"votes": 3867, "percentage": Decimal("26.44")},
        "IYODI HIRAM SAMUEL": {"votes": 50, "percentage": Decimal("0.34")},
        "KWEMO PIERRE": {"votes": 33, "percentage": Decimal("0.23")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1683, "percentage": Decimal("11.51")},
        "MATOMBA SERGE ESPOIR": {"votes": 193, "percentage": Decimal("1.32")},
        "MUNA AKERE TABENG": {"votes": 28, "percentage": Decimal("0.19")},
        "OSIH JOSHUA NAMBANGI": {"votes": 166, "percentage": Decimal("1.13")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 68, "percentage": Decimal("0.46")},
    },
    "Sanaga-Maritime": {
        "ATEKI SETA CAXTON": {"votes": 143, "percentage": Decimal("0.29")},
        "BELLO BOUBA MAIGARI": {"votes": 444, "percentage": Decimal("0.88")},
        "BIYA PAUL": {"votes": 22907, "percentage": Decimal("45.64")},
        "BOUGHA HAGBE JACQUES": {"votes": 103, "percentage": Decimal("0.21")},
        "ISSA TCHIROMA": {"votes": 10033, "percentage": Decimal("19.99")},
        "IYODI HIRAM SAMUEL": {"votes": 213, "percentage": Decimal("0.42")},
        "KWEMO PIERRE": {"votes": 143, "percentage": Decimal("0.29")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 14943, "percentage": Decimal("29.77")},
        "MATOMBA SERGE ESPOIR": {"votes": 258, "percentage": Decimal("0.51")},
        "MUNA AKERE TABENG": {"votes": 66, "percentage": Decimal("0.13")},
        "OSIH JOSHUA NAMBANGI": {"votes": 681, "percentage": Decimal("1.36")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 254, "percentage": Decimal("0.51")},
    },
    "Wouri": {
        "ATEKI SETA CAXTON": {"votes": 461, "percentage": Decimal("0.10")},
        "BELLO BOUBA MAIGARI": {"votes": 3181, "percentage": Decimal("0.67")},
        "BIYA PAUL": {"votes": 58465, "percentage": Decimal("12.41")},
        "BOUGHA HAGBE JACQUES": {"votes": 521, "percentage": Decimal("0.11")},
        "ISSA TCHIROMA": {"votes": 352062, "percentage": Decimal("74.73")},
        "IYODI HIRAM SAMUEL": {"votes": 4413, "percentage": Decimal("0.94")},
        "KWEMO PIERRE": {"votes": 661, "percentage": Decimal("0.14")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 40026, "percentage": Decimal("8.50")},
        "MATOMBA SERGE ESPOIR": {"votes": 1883, "percentage": Decimal("0.40")},
        "MUNA AKERE TABENG": {"votes": 523, "percentage": Decimal("0.11")},
        "OSIH JOSHUA NAMBANGI": {"votes": 6140, "percentage": Decimal("1.30")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 2783, "percentage": Decimal("0.59")},
    },
}

# Statistiques par département - RÉGION DU LITTORAL (page 13 du PDF)
DEPARTMENT_STATS_LITTORAL = {
    "Moungo": {
        "inscrits": 234020,
        "votants": 121101,
        "taux_participation": Decimal("51.75"),
        "taux_abstention": Decimal("48.25"),
        "bulletins_nuls": 1240,
        "suffrages_exprimes": 119861
    },
    "Nkam": {
        "inscrits": 27339,
        "votants": 14846,
        "taux_participation": Decimal("54.30"),
        "taux_abstention": Decimal("45.70"),
        "bulletins_nuls": 220,
        "suffrages_exprimes": 14626
    },
    "Sanaga-Maritime": {
        "inscrits": 100710,
        "votants": 50734,
        "taux_participation": Decimal("50.38"),
        "taux_abstention": Decimal("49.62"),
        "bulletins_nuls": 546,
        "suffrages_exprimes": 50188
    },
    "Wouri": {
        "inscrits": 977955,
        "votants": 474701,
        "taux_participation": Decimal("48.54"),
        "taux_abstention": Decimal("51.46"),
        "bulletins_nuls": 3582,
        "suffrages_exprimes": 471119
    },
}

# Résultats par département - RÉGION DU NORD (page 15 du PDF)
DEPARTMENT_RESULTS_NORD = {
    "Bénoué": {
        "ATEKI SETA CAXTON": {"votes": 4661, "percentage": Decimal("2.40")},
        "BELLO BOUBA MAIGARI": {"votes": 13868, "percentage": Decimal("7.14")},
        "BIYA PAUL": {"votes": 66362, "percentage": Decimal("34.16")},
        "BOUGHA HAGBE JACQUES": {"votes": 1469, "percentage": Decimal("0.75")},
        "ISSA TCHIROMA": {"votes": 96820, "percentage": Decimal("49.84")},
        "IYODI HIRAM SAMUEL": {"votes": 1194, "percentage": Decimal("0.61")},
        "KWEMO PIERRE": {"votes": 1264, "percentage": Decimal("0.65")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 2634, "percentage": Decimal("1.36")},
        "MATOMBA SERGE ESPOIR": {"votes": 1010, "percentage": Decimal("0.52")},
        "MUNA AKERE TABENG": {"votes": 1181, "percentage": Decimal("0.61")},
        "OSIH JOSHUA NAMBANGI": {"votes": 1085, "percentage": Decimal("0.56")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 2710, "percentage": Decimal("1.40")},
    },
    "Faro": {
        "ATEKI SETA CAXTON": {"votes": 503, "percentage": Decimal("2.05")},
        "BELLO BOUBA MAIGARI": {"votes": 725, "percentage": Decimal("2.95")},
        "BIYA PAUL": {"votes": 15550, "percentage": Decimal("63.34")},
        "BOUGHA HAGBE JACQUES": {"votes": 104, "percentage": Decimal("0.42")},
        "ISSA TCHIROMA": {"votes": 6527, "percentage": Decimal("26.59")},
        "IYODI HIRAM SAMUEL": {"votes": 103, "percentage": Decimal("0.42")},
        "KWEMO PIERRE": {"votes": 131, "percentage": Decimal("0.53")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 219, "percentage": Decimal("0.89")},
        "MATOMBA SERGE ESPOIR": {"votes": 123, "percentage": Decimal("0.50")},
        "MUNA AKERE TABENG": {"votes": 111, "percentage": Decimal("0.45")},
        "OSIH JOSHUA NAMBANGI": {"votes": 109, "percentage": Decimal("0.45")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 345, "percentage": Decimal("1.41")},
    },
    "Mayo-Louti": {
        "ATEKI SETA CAXTON": {"votes": 3036, "percentage": Decimal("3.43")},
        "BELLO BOUBA MAIGARI": {"votes": 6254, "percentage": Decimal("7.07")},
        "BIYA PAUL": {"votes": 23241, "percentage": Decimal("26.28")},
        "BOUGHA HAGBE JACQUES": {"votes": 855, "percentage": Decimal("0.97")},
        "ISSA TCHIROMA": {"votes": 49187, "percentage": Decimal("55.63")},
        "IYODI HIRAM SAMUEL": {"votes": 680, "percentage": Decimal("0.77")},
        "KWEMO PIERRE": {"votes": 630, "percentage": Decimal("0.71")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 963, "percentage": Decimal("1.09")},
        "MATOMBA SERGE ESPOIR": {"votes": 441, "percentage": Decimal("0.50")},
        "MUNA AKERE TABENG": {"votes": 655, "percentage": Decimal("0.74")},
        "OSIH JOSHUA NAMBANGI": {"votes": 545, "percentage": Decimal("0.62")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1935, "percentage": Decimal("2.19")},
    },
    "Mayo-Rey": {
        "ATEKI SETA CAXTON": {"votes": 2098, "percentage": Decimal("2.27")},
        "BELLO BOUBA MAIGARI": {"votes": 13029, "percentage": Decimal("14.12")},
        "BIYA PAUL": {"votes": 49773, "percentage": Decimal("53.93")},
        "BOUGHA HAGBE JACQUES": {"votes": 1322, "percentage": Decimal("1.43")},
        "ISSA TCHIROMA": {"votes": 21303, "percentage": Decimal("23.08")},
        "IYODI HIRAM SAMUEL": {"votes": 573, "percentage": Decimal("0.62")},
        "KWEMO PIERRE": {"votes": 832, "percentage": Decimal("0.90")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 635, "percentage": Decimal("0.69")},
        "MATOMBA SERGE ESPOIR": {"votes": 494, "percentage": Decimal("0.54")},
        "MUNA AKERE TABENG": {"votes": 577, "percentage": Decimal("0.63")},
        "OSIH JOSHUA NAMBANGI": {"votes": 498, "percentage": Decimal("0.54")},
        "TOMAINO HERMINE PATRICIA épouse NDAM NJOYA": {"votes": 1155, "percentage": Decimal("1.25")},
    },
}

# Statistiques par département - RÉGION DU NORD (page 15 du PDF)
DEPARTMENT_STATS_NORD = {
    "Bénoué": {
        "inscrits": 423422,
        "votants": 198943,
        "taux_participation": Decimal("46.98"),
        "taux_abstention": Decimal("53.02"),
        "bulletins_nuls": 4685,
        "suffrages_exprimes": 194258
    },
    "Faro": {
        "inscrits": 39057,
        "votants": 25026,
        "taux_participation": Decimal("64.08"),
        "taux_abstention": Decimal("35.92"),
        "bulletins_nuls": 476,
        "suffrages_exprimes": 24550
    },
    "Mayo-Louti": {
        "inscrits": 173359,
        "votants": 90404,
        "taux_participation": Decimal("52.15"),
        "taux_abstention": Decimal("47.85"),
        "bulletins_nuls": 1982,
        "suffrages_exprimes": 88422
    },
    "Mayo-Rey": {
        "inscrits": 157667,
        "votants": 94544,
        "taux_participation": Decimal("59.96"),
        "taux_abstention": Decimal("40.04"),
        "bulletins_nuls": 2255,
        "suffrages_exprimes": 92289
    },
}

# Statistiques globales (page 33 du PDF)
GLOBAL_STATS = {
    "total_inscrits": 8082692,
    "total_votants": 4668446,
    "taux_participation": Decimal("57.76"),
    "taux_abstention": Decimal("42.24"),
    "total_bulletins_nuls": 57620,
    "total_suffrages_exprimes": 4610826,
    # Cameroun
    "inscrits_cameroun": 8048473,
    "votants_cameroun": 4651670,
    # Diaspora
    "inscrits_diaspora": 34219,
    "votants_diaspora": 16776,
}

# Statistiques par région (page 33 du PDF - Récapitulatif général)
REGIONAL_STATS = {
    "AD": {"inscrits": 511932, "votants": 232096, "taux": Decimal("45.34"), "abstention": Decimal("54.66"), "nuls": 3096, "exprimes": 229000},
    "CE": {"inscrits": 1484347, "votants": 1036887, "taux": Decimal("69.85"), "abstention": Decimal("30.15"), "nuls": 7258, "exprimes": 1029629},
    "ES": {"inscrits": 394359, "votants": 263325, "taux": Decimal("66.77"), "abstention": Decimal("33.23"), "nuls": 2724, "exprimes": 260601},
    "EN": {"inscrits": 1261595, "votants": 734662, "taux": Decimal("58.23"), "abstention": Decimal("41.77"), "nuls": 17369, "exprimes": 717293},
    "LT": {"inscrits": 1340024, "votants": 661382, "taux": Decimal("49.36"), "abstention": Decimal("50.64"), "nuls": 5588, "exprimes": 655794},
    "NO": {"inscrits": 793505, "votants": 408917, "taux": Decimal("51.53"), "abstention": Decimal("48.47"), "nuls": 9398, "exprimes": 399519},
    "NW": {"inscrits": 628096, "votants": 297875, "taux": Decimal("47.43"), "abstention": Decimal("52.57"), "nuls": 2210, "exprimes": 295665},
    "OU": {"inscrits": 877580, "votants": 528969, "taux": Decimal("60.28"), "abstention": Decimal("39.72"), "nuls": 6438, "exprimes": 522531},
    "SU": {"inscrits": 326329, "votants": 288098, "taux": Decimal("88.28"), "abstention": Decimal("11.72"), "nuls": 1451, "exprimes": 286647},
    "SW": {"inscrits": 430706, "votants": 199459, "taux": Decimal("46.31"), "abstention": Decimal("53.69"), "nuls": 1792, "exprimes": 197667},
    # Diaspora
    "DA": {"inscrits": 20246, "votants": 9094, "taux": Decimal("44.92"), "abstention": Decimal("55.08"), "nuls": 173, "exprimes": 8921},
    "DAM": {"inscrits": 1721, "votants": 1244, "taux": Decimal("72.28"), "abstention": Decimal("27.72"), "nuls": 17, "exprimes": 1227},
    "DAS": {"inscrits": 1568, "votants": 693, "taux": Decimal("44.20"), "abstention": Decimal("55.80"), "nuls": 4, "exprimes": 689},
    "DE": {"inscrits": 10684, "votants": 5745, "taux": Decimal("53.77"), "abstention": Decimal("46.23"), "nuls": 102, "exprimes": 5643},
}

# Résultats par région pour chaque candidat (pages 34-35 du PDF)
REGIONAL_RESULTS = {
    "AD": {
        "BIYA PAUL": {"votes": 79256, "pct": Decimal("34.61")},
        "ISSA TCHIROMA": {"votes": 115258, "pct": Decimal("50.33")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 3414, "pct": Decimal("1.49")},
        "BELLO BOUBA MAIGARI": {"votes": 19744, "pct": Decimal("8.62")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 2281, "pct": Decimal("1.00")},
        "OSIH JOSHUA NAMBANGI": {"votes": 1307, "pct": Decimal("0.57")},
        "ATEKI SETA CAXTON": {"votes": 2997, "pct": Decimal("1.31")},
        "IYODI HIRAM SAMUEL": {"votes": 704, "pct": Decimal("0.31")},
        "MATOMBA SERGE ESPOIR": {"votes": 1020, "pct": Decimal("0.45")},
        "BOUGHA HAGBE JACQUES": {"votes": 1216, "pct": Decimal("0.53")},
        "KWEMO PIERRE": {"votes": 939, "pct": Decimal("0.41")},
        "MUNA AKERE TABENG": {"votes": 864, "pct": Decimal("0.38")},
    },
    "CE": {
        "BIYA PAUL": {"votes": 722153, "pct": Decimal("70.14")},
        "ISSA TCHIROMA": {"votes": 222654, "pct": Decimal("21.62")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 4331, "pct": Decimal("0.42")},
        "BELLO BOUBA MAIGARI": {"votes": 62118, "pct": Decimal("6.03")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 2829, "pct": Decimal("0.27")},
        "OSIH JOSHUA NAMBANGI": {"votes": 4436, "pct": Decimal("0.43")},
        "ATEKI SETA CAXTON": {"votes": 1449, "pct": Decimal("0.14")},
        "IYODI HIRAM SAMUEL": {"votes": 4339, "pct": Decimal("0.42")},
        "MATOMBA SERGE ESPOIR": {"votes": 2622, "pct": Decimal("0.25")},
        "BOUGHA HAGBE JACQUES": {"votes": 869, "pct": Decimal("0.08")},
        "KWEMO PIERRE": {"votes": 880, "pct": Decimal("0.09")},
        "MUNA AKERE TABENG": {"votes": 949, "pct": Decimal("0.09")},
    },
    "ES": {
        "BIYA PAUL": {"votes": 192543, "pct": Decimal("73.88")},
        "ISSA TCHIROMA": {"votes": 51660, "pct": Decimal("19.82")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 6214, "pct": Decimal("2.38")},
        "BELLO BOUBA MAIGARI": {"votes": 3833, "pct": Decimal("1.47")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 1003, "pct": Decimal("0.38")},
        "OSIH JOSHUA NAMBANGI": {"votes": 784, "pct": Decimal("0.30")},
        "ATEKI SETA CAXTON": {"votes": 1678, "pct": Decimal("0.64")},
        "IYODI HIRAM SAMUEL": {"votes": 665, "pct": Decimal("0.26")},
        "MATOMBA SERGE ESPOIR": {"votes": 687, "pct": Decimal("0.26")},
        "BOUGHA HAGBE JACQUES": {"votes": 744, "pct": Decimal("0.29")},
        "KWEMO PIERRE": {"votes": 435, "pct": Decimal("0.17")},
        "MUNA AKERE TABENG": {"votes": 355, "pct": Decimal("0.14")},
    },
    "EN": {
        "BIYA PAUL": {"votes": 329476, "pct": Decimal("45.93")},
        "ISSA TCHIROMA": {"votes": 303669, "pct": Decimal("42.34")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 7782, "pct": Decimal("1.08")},
        "BELLO BOUBA MAIGARI": {"votes": 28778, "pct": Decimal("4.01")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 9497, "pct": Decimal("1.32")},
        "OSIH JOSHUA NAMBANGI": {"votes": 3517, "pct": Decimal("0.49")},
        "ATEKI SETA CAXTON": {"votes": 18873, "pct": Decimal("2.63")},
        "IYODI HIRAM SAMUEL": {"votes": 2617, "pct": Decimal("0.36")},
        "MATOMBA SERGE ESPOIR": {"votes": 2712, "pct": Decimal("0.38")},
        "BOUGHA HAGBE JACQUES": {"votes": 4218, "pct": Decimal("0.59")},
        "KWEMO PIERRE": {"votes": 3732, "pct": Decimal("0.52")},
        "MUNA AKERE TABENG": {"votes": 2422, "pct": Decimal("0.34")},
    },
    "LT": {
        "BIYA PAUL": {"votes": 137679, "pct": Decimal("20.99")},
        "ISSA TCHIROMA": {"votes": 423557, "pct": Decimal("64.59")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 59447, "pct": Decimal("9.06")},
        "BELLO BOUBA MAIGARI": {"votes": 6757, "pct": Decimal("1.03")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 4047, "pct": Decimal("0.62")},
        "OSIH JOSHUA NAMBANGI": {"votes": 10904, "pct": Decimal("1.66")},
        "ATEKI SETA CAXTON": {"votes": 1225, "pct": Decimal("0.19")},
        "IYODI HIRAM SAMUEL": {"votes": 5206, "pct": Decimal("0.79")},
        "MATOMBA SERGE ESPOIR": {"votes": 3363, "pct": Decimal("0.51")},
        "BOUGHA HAGBE JACQUES": {"votes": 907, "pct": Decimal("0.14")},
        "KWEMO PIERRE": {"votes": 1756, "pct": Decimal("0.27")},
        "MUNA AKERE TABENG": {"votes": 946, "pct": Decimal("0.14")},
    },
    "NO": {
        "BIYA PAUL": {"votes": 154926, "pct": Decimal("38.78")},
        "ISSA TCHIROMA": {"votes": 173837, "pct": Decimal("43.51")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 4451, "pct": Decimal("1.11")},
        "BELLO BOUBA MAIGARI": {"votes": 33876, "pct": Decimal("8.48")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 6145, "pct": Decimal("1.54")},
        "OSIH JOSHUA NAMBANGI": {"votes": 2237, "pct": Decimal("0.56")},
        "ATEKI SETA CAXTON": {"votes": 10298, "pct": Decimal("2.58")},
        "IYODI HIRAM SAMUEL": {"votes": 2550, "pct": Decimal("0.64")},
        "MATOMBA SERGE ESPOIR": {"votes": 2068, "pct": Decimal("0.52")},
        "BOUGHA HAGBE JACQUES": {"votes": 3750, "pct": Decimal("0.94")},
        "KWEMO PIERRE": {"votes": 2857, "pct": Decimal("0.72")},
        "MUNA AKERE TABENG": {"votes": 2524, "pct": Decimal("0.63")},
    },
    "NW": {
        "BIYA PAUL": {"votes": 255188, "pct": Decimal("86.31")},
        "ISSA TCHIROMA": {"votes": 15392, "pct": Decimal("5.21")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 593, "pct": Decimal("0.20")},
        "BELLO BOUBA MAIGARI": {"votes": 5325, "pct": Decimal("1.80")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 500, "pct": Decimal("0.17")},
        "OSIH JOSHUA NAMBANGI": {"votes": 16292, "pct": Decimal("5.51")},
        "ATEKI SETA CAXTON": {"votes": 534, "pct": Decimal("0.18")},
        "IYODI HIRAM SAMUEL": {"votes": 367, "pct": Decimal("0.12")},
        "MATOMBA SERGE ESPOIR": {"votes": 409, "pct": Decimal("0.14")},
        "BOUGHA HAGBE JACQUES": {"votes": 222, "pct": Decimal("0.08")},
        "KWEMO PIERRE": {"votes": 187, "pct": Decimal("0.06")},
        "MUNA AKERE TABENG": {"votes": 656, "pct": Decimal("0.22")},
    },
    "OU": {
        "BIYA PAUL": {"votes": 201731, "pct": Decimal("38.61")},
        "ISSA TCHIROMA": {"votes": 244315, "pct": Decimal("46.76")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 4641, "pct": Decimal("0.89")},
        "BELLO BOUBA MAIGARI": {"votes": 7392, "pct": Decimal("1.41")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 49296, "pct": Decimal("9.43")},
        "OSIH JOSHUA NAMBANGI": {"votes": 5617, "pct": Decimal("1.07")},
        "ATEKI SETA CAXTON": {"votes": 2249, "pct": Decimal("0.43")},
        "IYODI HIRAM SAMUEL": {"votes": 1239, "pct": Decimal("0.24")},
        "MATOMBA SERGE ESPOIR": {"votes": 2276, "pct": Decimal("0.44")},
        "BOUGHA HAGBE JACQUES": {"votes": 1018, "pct": Decimal("0.19")},
        "KWEMO PIERRE": {"votes": 1801, "pct": Decimal("0.34")},
        "MUNA AKERE TABENG": {"votes": 956, "pct": Decimal("0.18")},
    },
    "SU": {
        "BIYA PAUL": {"votes": 260449, "pct": Decimal("90.86")},
        "ISSA TCHIROMA": {"votes": 17207, "pct": Decimal("6.00")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 5965, "pct": Decimal("2.08")},
        "BELLO BOUBA MAIGARI": {"votes": 542, "pct": Decimal("0.19")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 496, "pct": Decimal("0.17")},
        "OSIH JOSHUA NAMBANGI": {"votes": 772, "pct": Decimal("0.27")},
        "ATEKI SETA CAXTON": {"votes": 173, "pct": Decimal("0.06")},
        "IYODI HIRAM SAMUEL": {"votes": 409, "pct": Decimal("0.14")},
        "MATOMBA SERGE ESPOIR": {"votes": 198, "pct": Decimal("0.07")},
        "BOUGHA HAGBE JACQUES": {"votes": 281, "pct": Decimal("0.10")},
        "KWEMO PIERRE": {"votes": 64, "pct": Decimal("0.02")},
        "MUNA AKERE TABENG": {"votes": 91, "pct": Decimal("0.03")},
    },
    "SW": {
        "BIYA PAUL": {"votes": 135975, "pct": Decimal("68.79")},
        "ISSA TCHIROMA": {"votes": 45047, "pct": Decimal("22.79")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 1677, "pct": Decimal("0.85")},
        "BELLO BOUBA MAIGARI": {"votes": 2118, "pct": Decimal("1.07")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 461, "pct": Decimal("0.23")},
        "OSIH JOSHUA NAMBANGI": {"votes": 9875, "pct": Decimal("5.00")},
        "ATEKI SETA CAXTON": {"votes": 428, "pct": Decimal("0.22")},
        "IYODI HIRAM SAMUEL": {"votes": 496, "pct": Decimal("0.25")},
        "MATOMBA SERGE ESPOIR": {"votes": 542, "pct": Decimal("0.27")},
        "BOUGHA HAGBE JACQUES": {"votes": 290, "pct": Decimal("0.15")},
        "KWEMO PIERRE": {"votes": 210, "pct": Decimal("0.11")},
        "MUNA AKERE TABENG": {"votes": 548, "pct": Decimal("0.28")},
    },
    # Diaspora
    "DA": {
        "BIYA PAUL": {"votes": 3045, "pct": Decimal("34.13")},
        "ISSA TCHIROMA": {"votes": 4906, "pct": Decimal("54.99")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 566, "pct": Decimal("6.34")},
        "BELLO BOUBA MAIGARI": {"votes": 39, "pct": Decimal("0.44")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 85, "pct": Decimal("0.95")},
        "OSIH JOSHUA NAMBANGI": {"votes": 64, "pct": Decimal("0.72")},
        "ATEKI SETA CAXTON": {"votes": 28, "pct": Decimal("0.31")},
        "IYODI HIRAM SAMUEL": {"votes": 85, "pct": Decimal("0.95")},
        "MATOMBA SERGE ESPOIR": {"votes": 20, "pct": Decimal("0.22")},
        "BOUGHA HAGBE JACQUES": {"votes": 10, "pct": Decimal("0.11")},
        "KWEMO PIERRE": {"votes": 8, "pct": Decimal("0.09")},
        "MUNA AKERE TABENG": {"votes": 16, "pct": Decimal("0.18")},
    },
    "DAM": {
        "BIYA PAUL": {"votes": 315, "pct": Decimal("25.67")},
        "ISSA TCHIROMA": {"votes": 819, "pct": Decimal("66.75")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 68, "pct": Decimal("5.54")},
        "BELLO BOUBA MAIGARI": {"votes": 3, "pct": Decimal("0.24")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 3, "pct": Decimal("0.24")},
        "OSIH JOSHUA NAMBANGI": {"votes": 4, "pct": Decimal("0.33")},
        "ATEKI SETA CAXTON": {"votes": 1, "pct": Decimal("0.08")},
        "IYODI HIRAM SAMUEL": {"votes": 12, "pct": Decimal("0.98")},
        "MATOMBA SERGE ESPOIR": {"votes": 1, "pct": Decimal("0.08")},
        "BOUGHA HAGBE JACQUES": {"votes": 0, "pct": Decimal("0.00")},
        "KWEMO PIERRE": {"votes": 1, "pct": Decimal("0.08")},
        "MUNA AKERE TABENG": {"votes": 0, "pct": Decimal("0.00")},
    },
    "DAS": {
        "BIYA PAUL": {"votes": 166, "pct": Decimal("24.09")},
        "ISSA TCHIROMA": {"votes": 470, "pct": Decimal("68.21")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 33, "pct": Decimal("4.79")},
        "BELLO BOUBA MAIGARI": {"votes": 4, "pct": Decimal("0.58")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 3, "pct": Decimal("0.44")},
        "OSIH JOSHUA NAMBANGI": {"votes": 5, "pct": Decimal("0.73")},
        "ATEKI SETA CAXTON": {"votes": 1, "pct": Decimal("0.15")},
        "IYODI HIRAM SAMUEL": {"votes": 5, "pct": Decimal("0.73")},
        "MATOMBA SERGE ESPOIR": {"votes": 1, "pct": Decimal("0.15")},
        "BOUGHA HAGBE JACQUES": {"votes": 1, "pct": Decimal("0.15")},
        "KWEMO PIERRE": {"votes": 0, "pct": Decimal("0.00")},
        "MUNA AKERE TABENG": {"votes": 0, "pct": Decimal("0.00")},
    },
    "DE": {
        "BIYA PAUL": {"votes": 1277, "pct": Decimal("22.63")},
        "ISSA TCHIROMA": {"votes": 3543, "pct": Decimal("62.79")},
        "LIBII LI NGUE NGUE CABRAL": {"votes": 599, "pct": Decimal("10.61")},
        "BELLO BOUBA MAIGARI": {"votes": 16, "pct": Decimal("0.28")},
        "TOMAINO HERMINE PATRICIA épse NDAM NJOYA": {"votes": 26, "pct": Decimal("0.46")},
        "OSIH JOSHUA NAMBANGI": {"votes": 27, "pct": Decimal("0.48")},
        "ATEKI SETA CAXTON": {"votes": 1, "pct": Decimal("0.02")},
        "IYODI HIRAM SAMUEL": {"votes": 134, "pct": Decimal("2.37")},
        "MATOMBA SERGE ESPOIR": {"votes": 6, "pct": Decimal("0.11")},
        "BOUGHA HAGBE JACQUES": {"votes": 6, "pct": Decimal("0.11")},
        "KWEMO PIERRE": {"votes": 3, "pct": Decimal("0.05")},
        "MUNA AKERE TABENG": {"votes": 5, "pct": Decimal("0.09")},
    },
}
